### PR TITLE
use custom snomask letter for SAMOVE

### PR DESCRIPTION
**Pull request by hoerup**

### CODE REVIEW

**Comment by hoerup** [comment]
@SadieCat what's the chance of getting this merged ?

**Comment by SadieCat** [comment]
Thanks for the reminder. I'll merge it later today once I've fixed the CI issues.

**Comment by SadieCat** [comment]
Can you rebase this branch against the latest changes in master? Once that is done and CI is green I can merge. Thanks.

**Comment by hoerup** [comment]
Done

**Pull request merged**
